language: php
php:
  - '7.2'
  - '7.3'
  - 'nightly'
services:
  - 'redis-server'
  - 'mysql'
before_script:
  - composer install --dev
script:
  - vendor/bin/phpunit --testsuite unit
  - vendor/bin/phpunit --testsuite integration
  - vendor/bin/psalm
