version: '3'
services:
  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_ROOT_PASSWORD: ''
    ports:
      - 3306:3306
